### ISSUE TITLE
[bug] 만보 달성시 버튼을 누르지 않았는데도 캐릭터가 바뀌는 현상 

### ISSUE THREAD

**Issue by OneMoreThink** [FineAppleJuices/AppleJuice#32]
## 버그 보고
- 만보 달성 이후 나타나는 오른쪽 상단 버튼을 누르지 않아도 자동으로 메인화면의 에셋이 주스로 교체됩니다.
- 만보 걸어도 버튼이 안뜹니다. 배경화면 주스만 바뀝니다. 각종 값들의 초기화가 필요한 것으로 보입니다.
- 냉장고에 걸음 수 갱신이 다음날 되어도 갱신이 안됩니다. 버튼을 눌렀을 때의 값만 남아있습니다.

### 설명
- 설계대로면 버튼을 누르기 전까지는 메인화면의 캐릭터가 변경되서는 안됩니다. 

### 재현 방법
1. 걸음수 만보를 달성합니다.
2. WatchApp을 켭니다. 

### 예상 동작
- 조건(만보이상 걸음수)가 달성되면 오른쪽 상단에 주스 만들기 버튼이 나타납니다. (이때까지는 사과 캐릭터가 유지됩니다.)
- 해당 버튼을 누르면 주스 만들기 애니메이션이 재생됩니다. 
- 애니메이션이 재생된 후 메인화면에 캐릭터가 사과에서 주스로 변경됩니다. 

### 실제 동작
- 조건이 달성되면 버튼을 누르지 않아도 메인 화면의 캐릭터가 사과에서 주스로 변경됩니다.
- 조건 달성시 오른쪽 상단 버튼이 나타지만 눌러도 주스 애니메이션이 재생되지 않습니다. 
- 오른쪽 상단 버튼을 누르면 해당 버튼이 사라집니다. 

### 환경
- OS: WatchOS 10.6.1
- 기기:Apple Watch SE(2세대)
- 버전: 1.0.0 Testflight

**Comment by norang00** [comment]
- 만보 달성 이후 나타나는 오른쪽 상단 버튼을 누르지 않아도 자동으로 메인화면의 에셋이 주스로 교체됩니다.
-> 만보 달성 이후 버튼 상호작용없이 배경애셋이 바뀌도록 되어있었습니다. isBackgroundChanged 변수를 추가하여 버튼 클릭시에 배경화면이 바뀌도록 설정하였습니다.

- 만보 걸어도 버튼이 안뜹니다. 배경화면 주스만 바뀝니다. 각종 값들의 초기화가 필요한 것으로 보입니다.
-> juiceButtonVisible 값이 걸음 수가 10,000에 도달할 때 true로 설정되는 로직이 누락되었습니다. mainView ZStack 의 onChange 메서드로 sm.stepCount가 만보를 넘으면 juiceButtonVisible이 true가 되도록 설정을 추가했습니다. + 해당 일자에 만보가 달성되었는지를 확인, 이미 되어있는 경우에는 다시 false 가 되도록 합니다.

- 냉장고에 걸음 수 갱신이 다음날 되어도 갱신이 안됩니다. 버튼을 눌렀을 때의 값만 남아있습니다.
-> 앱의 초기화시에 마지막 접속날짜를 저장하도록 되어있었습니다;; AppDelegate 를 이용하여 앱이 액티브에서 나갈 때 (종료되거나 백그라운드모드에 들어갈때) 마지막 접속 날짜를 저장합니다.
